### ISSUE TITLE
Replace user-home with os.homedir()

### ISSUE THREAD

**Issue by mojavelinux** [strugee/node-cache-directory#2]
The user-home package (which depends on the os-homedir polyfill) is deprecated. More important, the xdg-basedir package has already switched to using os.homedir() directly. Therefore, to use a consistent strategy for resolving the user home directory for all platforms, and to be consistent with Node's behavior, this package should also use os.homedir() directly. It also cuts out a dependency (and an unnecessary one at that).

**Comment by strugee** [comment]
AFAICT this wouldn't break Node 4. So I'd take a PR.

**Comment by mojavelinux** [comment]
Ask and you shall receive!

**Comment by mojavelinux** [comment]
Sent!
